export const REQ_GET_DATA = "REQ_GET_DATA"
export const SUCC_GET_DATA = "SUCC_GET_DATA"
export const FAIL_GET_DATA = "FAIL_GET_DATA"


export const REQ_SEARCH_DATA = "REQ_SEARCH_DATA"
export const SUCC_SEARCH_DATA = "SUCC_SEARCH_DATA"
export const FAIL_SEARCH_DATA = "FAIL_SEARCH_DATA"